name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: With requirements
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          requirements: requirements.yml
          options: --inventory hosts
      - name: With requirements bundle
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          requirements: requirements-bundle.yml
          options: --inventory hosts
      - name: With vault password
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          vault_password: test
          options: --inventory hosts
      - name: With sudo
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          sudo: true
          options: --inventory hosts
